# Generated by Django 4.2.27 on 2026-01-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddataset',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
